apiVersion: apps/v1
kind: Deployment
metadata:
  name: edb-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: edb-reader
    app.kubernetes.io/part-of: edgelessdb-demo
    app.kubernetes.io/version: {{ .Values.image.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edb-reader
      app.kubernetes.io/version: {{ .Values.image.version }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edb-reader
        app.kubernetes.io/part-of: edgelessdb-demo
        app.kubernetes.io/version: {{ .Values.image.version }}
        marblerun/marbletype: reader
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: OE_SIMULATION
            value: "{{ .Values.simulation }}"
          - name: EDG_DB_HOST
            value: "edgelessdb-sql-api.edgelessdb.svc.cluster.local:{{ .Values.sqlPort }}"
          image: "{{ .Values.image.repository }}/edb-demo/reader:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: edb-reader
          ports:
          - containerPort: 8008
            name: http
---
apiVersion: v1
kind: Service
metadata:
  name: edb-reader-http
  namespace: {{ .Release.namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: edb-reader
    app.kubernetes.io/version: {{ .Values.image.version }}
  ports:
  - name: http
    port: 8008
    targetPort: 8008
