apiVersion: apps/v1
kind: Deployment
metadata:
  name: edb-writer
  namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/name: edb-writer
    app.kubernetes.io/part-of: edgelessdb-demo
    app.kubernetes.io/version: {{ .Values.image.version }}
spec:
  replicas: 1
  selector:
    matchlabels:
      app.kubernetes.io/name: edb-writer
      app.kubernetes.io/version: {{ .Values.image.version }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edb-writer
        app.kubernetes.io/part-of: edgelessdb-demo
        app.kubernetes.io/version: {{ .Values.image.version }}
        marblerun/marbletype: writer
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: OE_SIMULATION
            value: {{ .Values.simulation }}
          image: "{{ .Values.image.repository }}/edb-demo/writer:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: edb-writer
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
